modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="saoswords"
version="1.0.0"
displayName="SAO Swords"
description='''Adds the Elucidator, Dark Repulser and Excalibur swords.'''

[[dependencies.saoswords]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.saoswords]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
